# should be mounted to a docker container of prometheus as a volume:/etc/prometheus/prometheus.yml
global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]