apiVersion: v1
kind: Service
metadata:
  name: app-nodeport
  labels:
    type: service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008

    