name: Hivebox CI/CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12"
      - name: install dependancies
        run: | 
          pip install -r requirements.txt
          pip install pytest
      - name: unit testing
        run: pytest tests/*
  Pylinting:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: install dependancies
        run: | 
          pip install -r requirements.txt
      - name: installing PyLint
        run: pip install pylint
      - name: linting the code
        run: pylint $(git ls-files '*.py')
  Sonarqube_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running sonarqube to scan code
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        with:
          projectBaseDir: ./app
      - name: checking if sonarqube passed or not
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
  Hadolinting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linting Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
  Dockerizing:
    runs-on: ubuntu-latest
    needs: Hadolinting
    steps:
      - uses: actions/checkout@v4
      - name: Building Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hivebox:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/hivebox:latest
          docker logout
